### ISSUE TITLE
Click/drag off screen crashes app

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-gui#6]
![2020-02-11 21 02 20](https://user-images.githubusercontent.com/22067021/74301923-e03b8000-4d11-11ea-80e1-230ec3323a10.gif)

Click the camera and drag off screen then a crash happens:

```py
(dev) ➜  pyvista_gui git:(feat/expand) python -m pyvista_gui
DEBUG:pyvista_gui.gui:GUI initialized
DEBUG:matplotlib.pyplot:Loaded backend macosx version unknown.
DEBUG:matplotlib.pyplot:Loaded backend qt5agg version unknown.
DEBUG:matplotlib.pyplot:Loaded backend Qt5Agg version unknown.
DEBUG:asyncio:Using selector: KqueueSelector
Traceback (most recent call last):
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/vtkmodules/qt/QVTKRenderWindowInteractor.py", line 474, in mouseMoveEvent
    ctrl, shift, chr(0), 0, None)
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/vtkmodules/qt/QVTKRenderWindowInteractor.py", line 420, in _setEventInformation
    scale = self._getPixelRatio()
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/vtkmodules/qt/QVTKRenderWindowInteractor.py", line 412, in _getPixelRatio
    return QApplication.devicePixelRatio()
TypeError: devicePixelRatio(self): first argument of unbound method must have type 'QGuiApplication'
[1]    37123 abort      python -m pyvista_gui
```

**Comment by akaszynski** [comment]
This seems to be an internal, `vtk` error.  We can override it or protect it with a `super` and catch the error.

**Comment by zakaria220** [comment]
I faced the same issue when using QVTKRenderWindowInteractor on a remote desktop, I opened an issue on VTK gitlab repo: https://gitlab.kitware.com/vtk/vtk/-/issues/17854 

If anyone needs an urgent fix for this issue, this dirty workaround can do the job:

```python
_getPixelRatio_BUG = QVTKRenderWindowInteractor._getPixelRatio
def _getPixelRatio_WORKAROUND(self):
	try:
		return _getPixelRatio_BUG()
	except Exception as err:
		print("Exception QVTKRenderWindowInteractor._getPixelRatio: {0}".format(err))
		return Qt.QApplication.instance().devicePixelRatio()
setattr(QVTKRenderWindowInteractor, '_getPixelRatio_WORKAROUND', _getPixelRatio_WORKAROUND)
QVTKRenderWindowInteractor._getPixelRatio = _getPixelRatio_WORKAROUND
```

I added these lines to my `main` function, right before calling `app = Qt.QApplication(sys.argv)`

**Comment by akaszynski** [comment]
Nice fix @zakaria220 

@banesullivan, should we consider incorporating this into `pyvista`?  Perhaps in `qt_plotting`?  We can then conditionally add it for unpatched versions of `vtk`.

**Comment by banesullivan** [comment]
Ah, that's a nifty little hack of a solution! Thanks, @zakaria220!

@akaszynski: I'm all for adding it directly into `pyvista` and just overriding the method on our class rather than monkey-patching

**Comment by ali-zakaria** [comment]
VTK 9.0.0 has been released with a fix https://github.com/Kitware/VTK/releases/tag/v9.0.0
